---
title: "Measurement_Final_Project"
author: "Ruiting Shen, Ivy Qiu"
format: pdf
editor_options: 
  chunk_output_type: console
---

```{r}
#| output: false
#| warning: false
setwd("~/Desktop/Measurement/measurement_final_project/")
library(tidyverse)
library(mirt)
```


# Initial data processing 
```{r}
d <- read_csv("data/genpsych_russell_2024_gemma.csv")

d_resp <- d |>
  select(id, item, resp) |>
  pivot_wider(names_from = item, values_from = resp) |> 
  arrange(desc(-id))

item_cols <- names(d_resp)[-1]
item_order <- order(as.integer(str_extract(item_cols, "\\d+")))
item_cols_sorted <- item_cols[item_order]


########Those are the two datasets we will use later###########
d_resp <- d_resp |>
  select(id, all_of(item_cols_sorted))

d_demo <- d |>
  select(id, starts_with("cov_")) |>
  distinct() |> 
  arrange(desc(-id))
###############################################################
```

# PART 2: Working with “item responses”

Here we will don a FA and fit an IRT (use GPCM) to those response data (d_resp)

```{r}

```


# PART 3: Clustering
Here let's use those demographics data and turn everything into binary and then fit a LCA 
```{r}

```




